//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;
using UmbracoInstagram.Abstract.IModels;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Post</summary>
	[PublishedContentModel("post")]
	public partial class Post : Wall
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "post";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Post(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Post, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// PostDate
		///</summary>
		[ImplementPropertyType("postDate")]
		public DateTime PostDate
		{
			get { return this.GetPropertyValue<DateTime>("postDate"); }
		}

		///<summary>
		/// PostImage
		///</summary>
		[ImplementPropertyType("postImage")]
		public IPublishedContent PostImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("postImage"); }
		}

		///<summary>
		/// PostText
		///</summary>
		[ImplementPropertyType("postText")]
		public string PostText
		{
			get { return this.GetPropertyValue<string>("postText"); }
		}
	}
}
